
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class DataPC extends javax.swing.JFrame {

    /**
     * Creates new form DataPC
     */
    public DataPC() {
        initComponents();
        tampil();
    }
    
    DefaultTableModel tabel;
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;

    public void tampil() {

        tabel = new DefaultTableModel();

        tabel.addColumn("Kode");
        tabel.addColumn("Nama PC");
        tabel.addColumn("Spesifikasi");
        tabel.addColumn("Harga sewa/hari");

        final String tampil_pc = "SELECT * FROM tb_pc";

        try (Connection conn = koneksi.getConnection();
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(tampil_pc)) {

          while (rs.next()) {
            int id = rs.getInt("id");
            String nama = rs.getString("nama_pc");
            String spek = rs.getString("spesifikasi");
            String harga = rs.getString("harga_sewa");
            tabel.addRow(new Object[]{id, nama, spek, harga});
          }
        } catch (SQLException se) {
          se.printStackTrace();
        }

        tb_pc.setModel(tabel);
    }
    
    public void bersih() {
        fPC.setText("");
        fSpek.setText("");
        fHarga.setText("");
        tID.setText("#");
    }
    
    public void cetak(){
    Document doc = new Document();
    try {
        PdfWriter.getInstance(doc, new FileOutputStream("laporan-pc.pdf"));
        doc.open();

        Font fontTebal = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
        
        Paragraph jdl = new Paragraph("Laporan data pc", fontTebal);
        jdl.setAlignment(Paragraph.ALIGN_CENTER);
        doc.add(jdl);

        PdfPTable table = new PdfPTable(4);

        doc.add(new Paragraph("\n"));
        
        PdfPCell cellId = new PdfPCell(new Paragraph("Kode"));
        table.addCell(cellId);
        
        PdfPCell cellNama = new PdfPCell(new Paragraph("Nama PC"));
        table.addCell(cellNama);
        
        PdfPCell cellSpek = new PdfPCell(new Paragraph("Spesifikasi"));
        table.addCell(cellSpek);
        
        PdfPCell cellHarga = new PdfPCell(new Paragraph("Harga sewa/hari"));
        table.addCell(cellHarga);
        

        Connection conn = koneksi.getConnection();

        String query = "SELECT * FROM tb_pc";

        Statement statement = conn.createStatement();
        ResultSet hasil = statement.executeQuery(query);

        while (hasil.next()) {
          String id             = hasil.getString("id");
          String nama           = hasil.getString("nama_pc");
          String spesifikasi    = hasil.getString("spesifikasi");
          String harga          = hasil.getString("harga_sewa");

          table.addCell(id);
          table.addCell(nama);
          table.addCell(spesifikasi);
          table.addCell(harga);
        }

        doc.add(table);
        JOptionPane.showMessageDialog(null, "Mencetak data pc Berhasil, file sudah dibuat", "Infromasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            doc.close();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_pc = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fPC = new javax.swing.JTextField();
        fSpek = new javax.swing.JTextField();
        fHarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tb_pc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_pc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_pcMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_pc);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Input Data PC");

        jLabel2.setText("Nama PC");

        jLabel3.setText("Spesifikasi");

        jLabel4.setText("Harga sewa/hari");

        fPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fPCActionPerformed(evt);
            }
        });

        jButton1.setText("ubah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("bersihkan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("cetak");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("ID:");

        tID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tID.setText("#");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fSpek)
                                    .addComponent(fPC)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(fHarga))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(194, 194, 194)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fSpek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton3)
                                    .addComponent(jButton4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(tID)))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fPCActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nama         = fPC.getText();
        String spek         = fSpek.getText();
        String harga        = fHarga.getText();
        
        if(fPC.getText().equals("") || fSpek.getText().equals("") || fHarga.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Inputan tidak boleh kosong", "Informasi", JOptionPane.YES_OPTION);
        } else {
            try (Connection conn = koneksi.getConnection()) {
                final String tambah_pc = "INSERT INTO tb_pc (nama_pc, spesifikasi, harga_sewa)"
                                          + " VALUES (?, ?, ?)";

                try (PreparedStatement pstmt = conn.prepareStatement(tambah_pc)) {
                  pstmt.setString(1, nama);
                  pstmt.setString(2, spek);
                  pstmt.setString(3, harga);

                  pstmt.executeUpdate();

                  JOptionPane.showMessageDialog(null, "Menyimpan data PC Berhasil", "Infromasi", JOptionPane.INFORMATION_MESSAGE);
                  tampil();
                  bersih();
                } catch (SQLException se) {
                  se.printStackTrace();
                }
              } catch (SQLException se) {
                se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tb_pcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_pcMouseClicked
        // TODO add your handling code here:
        int baris           = tb_pc.getSelectedRow();
        String id           = tabel.getValueAt(baris, 0).toString();
        String nama         = tabel.getValueAt(baris, 1).toString();
        String spek         = tabel.getValueAt(baris, 2).toString();
        String harga        = tabel.getValueAt(baris, 3).toString();
        
        tID.setText(String.valueOf(id));
        fPC.setText(nama);
        fSpek.setText(spek);
        fHarga.setText(harga);

    }//GEN-LAST:event_tb_pcMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id           = tID.getText();
        String nama         = fPC.getText();
        String spek         = fSpek.getText();
        String harga        = fHarga.getText();
        
        try (Connection conn = koneksi.getConnection()) {
          final String ubah_pc = "UPDATE tb_pc SET nama_pc = ?, spesifikasi = ?, harga_sewa = ? WHERE id = ?";

          try (PreparedStatement pstmt = conn.prepareStatement(ubah_pc)) {
            pstmt.setString(1, nama);
            pstmt.setString(2, spek);
            pstmt.setString(3, harga);
            pstmt.setString(4, id);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(null, "Mengubah data PC Berhasil", "Infromasi", JOptionPane.INFORMATION_MESSAGE);
            tampil();
            bersih();
          } catch (SQLException se) {
            se.printStackTrace();
          }
        } catch (SQLException se) {
          se.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String id = tID.getText();
        
        int yes = JOptionPane.showConfirmDialog(null, "Hapus data PC ini?","Perhatian!!", JOptionPane.YES_NO_OPTION);
        
        if(yes == 0) {
            try (Connection conn = koneksi.getConnection()) {
              final String hapus_pc = "DELETE FROM tb_pc WHERE id = ?";

              try (PreparedStatement pstmt = conn.prepareStatement(hapus_pc)) {
                pstmt.setString(1, id);

                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Menghapus data PC Berhasil", "Infromasi", JOptionPane.INFORMATION_MESSAGE);
                tampil();
                bersih();
              } catch (SQLException se) {
                se.printStackTrace();
              }
            } catch (SQLException se) {
              se.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cetak();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fHarga;
    private javax.swing.JTextField fPC;
    private javax.swing.JTextField fSpek;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tID;
    private javax.swing.JTable tb_pc;
    // End of variables declaration//GEN-END:variables
}
